# Generated by Django 5.1.6 on 2025-03-15 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quiz_master', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('waiting', '待機中'), ('in_progress', '進行中'), ('completed', '完了')], default='waiting', max_length=20)),
                ('current_question', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sample_app.quizcategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuizParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sample_app.quizsession')),
            ],
        ),
    ]
